version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.react
    container_name: cpc-client
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app
    depends_on:
      - express-api

  express-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.express
    container_name: cpc-server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app